"""Learning foundation contracts and persistence for EDGE HUNTER."""

from app.learning.models import (
    LearningDirection,
    LearningFeatureSnapshot,
    LearningRecord,
    LearningRecordStatus,
    LearningSourceType,
)
from app.learning.feature_store import (
    DuplicateFeatureSnapshotError,
    FeatureSnapshot,
    FeatureSnapshotError,
    FeatureSnapshotImmutableError,
    FeatureStore,
)
from app.learning.records import (
    LearningRecordBuildError,
    LearningRecordBuilder,
)
from app.learning.labels import (
    LearningOutcome,
    OutcomeLabelEngine,
    OutcomeResolution,
    OutcomeResolutionState,
)
from app.learning.dataset import (
    DatasetBuildError,
    DatasetBuildResult,
    DatasetExclusionReason,
    DatasetRow,
    DatasetSplit,
    DatasetSplitPolicy,
    DatasetVersion,
    LearningDatasetManager,
)
from app.learning.dataset_repository import (
    DatasetVersionImmutableError,
    DatasetVersionPersistenceError,
    DatasetVersionRepository,
)
from app.learning.repository import (
    DuplicateLearningRecordError,
    LearningRecordRepository,
    LearningRecordStateError,
)

from app.learning.training import (
    LearningTrainingPipeline,
    PreparedDataset,
    TrainingConfig,
    TrainingPipelineError,
    TrainingResult,
    TrainingRun,
    TrainingStage,
    TrainingStatus,
)
from app.learning.training_repository import TrainingRunPersistenceError, TrainingRunRepository

from app.learning.registry import (
    EvaluationStatus,
    ModelEvaluation,
    ModelRegistry,
    ModelRegistryError,
    ModelVersion,
    ModelVersionStatus,
)
from app.learning.model_registry_repository import ModelRegistryPersistenceError, ModelRegistryRepository
from app.learning.evaluation import ModelEvaluationEngine

__all__ = [
    "DuplicateFeatureSnapshotError",
    "DuplicateLearningRecordError",
    "FeatureSnapshot",
    "FeatureSnapshotError",
    "FeatureSnapshotImmutableError",
    "FeatureStore",
    "LearningDirection",
    "LearningFeatureSnapshot",
    "LearningRecord",
    "LearningRecordBuildError",
    "LearningRecordBuilder",
    "LearningRecordRepository",
    "LearningRecordStateError",
    "LearningRecordStatus",
    "LearningOutcome",
    "OutcomeLabelEngine",
    "OutcomeResolution",
    "OutcomeResolutionState",
    "LearningSourceType",
    "DatasetBuildError",
    "DatasetBuildResult",
    "DatasetExclusionReason",
    "DatasetRow",
    "DatasetSplit",
    "DatasetSplitPolicy",
    "DatasetVersion",
    "LearningDatasetManager",
    "DatasetVersionImmutableError",
    "DatasetVersionPersistenceError",
    "DatasetVersionRepository",
    "LearningTrainingPipeline",
    "PreparedDataset",
    "TrainingConfig",
    "TrainingPipelineError",
    "TrainingResult",
    "TrainingRun",
    "TrainingStage",
    "TrainingStatus",
    "TrainingRunPersistenceError",
    "TrainingRunRepository",
    "EvaluationStatus",
    "ModelEvaluation",
    "ModelEvaluationEngine",
    "ModelRegistry",
    "ModelRegistryError",
    "ModelRegistryPersistenceError",
    "ModelRegistryRepository",
    "ModelVersion",
    "ModelVersionStatus",
    "L8EvaluationEngine",
    "L8EvaluationError",
    "L8EvaluationReport",
    "L8EvaluationStatus",
    "L8EvaluationType",
    "StabilitySummary",
    "L8EvaluationPersistenceError",
    "L8EvaluationRepository",
    "LearnedPolicyError",
    "LearnedPolicyVersion",
    "PolicyMode",
    "PolicyType",
    "LearnedPolicyPersistenceError",
    "LearnedPolicyRepository",
    "AIInferenceResult",
    "AIModelInferenceAdapter",
    "ClassicLearnedPolicyAdapter",
    "ICTLearnedPolicyAdapter",
    "LearnedPolicyApplicationError",
    "LearnedPolicyService",
    "LearnedStrategyAdapter",
    "SMCLearnedPolicyAdapter",
    "ShadowPolicyResult",
    "CandidateStatus",
    "L10RepositoryError",
    "LearningCandidate",
    "LearningCycle",
    "LearningCycleRepository",
    "LearningCycleStatus",
    "LearningState",
    "MonitoringSnapshot",
    "ProductionModelState",
    "ProductionStateRepository",
    "PromotionHistoryEntry",
    "ContinuousLearningOrchestrator",
    "LearningCycleConfig",
    "LearningCycleError",
    "LearningCycleRequest",
    "LearningScheduler",
    "LearningTrigger",
    "MonitoringService",
    "ProductionSafety",
    "PromotionEvidence",
    "PromotionGate",
    "PromotionGateResult",
    "PromotionPolicy",
    "RollbackPolicy",
]
from app.learning.oos_evaluation import (
    L8EvaluationEngine,
    L8EvaluationError,
    L8EvaluationReport,
    L8EvaluationStatus,
    L8EvaluationType,
    StabilitySummary,
)
from app.learning.advanced_evaluation_repository import (
    L8EvaluationPersistenceError,
    L8EvaluationRepository,
)

from app.learning.policies import LearnedPolicyError, LearnedPolicyVersion, PolicyMode, PolicyType
from app.learning.policy_repository import LearnedPolicyPersistenceError, LearnedPolicyRepository
from app.learning.policy_adapters import (
    AIInferenceResult,
    AIModelInferenceAdapter,
    ClassicLearnedPolicyAdapter,
    ICTLearnedPolicyAdapter,
    LearnedPolicyApplicationError,
    LearnedPolicyService,
    LearnedStrategyAdapter,
    SMCLearnedPolicyAdapter,
    ShadowPolicyResult,
)

from app.learning.continuous_repository import (
    CandidateStatus,
    L10RepositoryError,
    LearningCandidate,
    LearningCycle,
    LearningCycleRepository,
    LearningCycleStatus,
    LearningState,
    MonitoringSnapshot,
    ProductionModelState,
    ProductionStateRepository,
    PromotionHistoryEntry,
)
from app.learning.continuous import (
    ContinuousLearningOrchestrator,
    LearningCycleConfig,
    LearningCycleError,
    LearningCycleRequest,
    LearningScheduler,
    LearningTrigger,
    MonitoringService,
    ProductionSafety,
    PromotionEvidence,
    PromotionGate,
    PromotionGateResult,
    PromotionPolicy,
    RollbackPolicy,
)
